server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: pimetric-service

logging:
  level:
    de:
      bluewhale:
        iot: WARN
    org:
      springframework: ERROR
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level)
            %logger.%M - %msg%n'

# Health check for cloud deployment
# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints-enabling-endpoints
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: metrics,health,info,prometheus
