- hosts: sabiFrontend
  vars_files:
    - ./group_vars/sabiFrontend.yml
  tasks:
    - name: Adding existing user "sabi" to group video for being able to use vcgencmd
      user:
        name: sabi
        groups: video
        append: yes
    - name: Stop existing webservice service
      service:
        name: sabi
        state: stopped
    - name: Copy new jar file
      copy:
        src: /Users/schubert/dev/Intellij-wss/github/sabi/sabi-webclient/target/sabi-webclient-1.0-SNAPSHOT.jar
        dest: /var/sabi/sabi-webclient.jar
        owner: sabi
        group: sabi
        mode: '0500'
    - name: Copy JVM config file
      copy:
        src: /Users/schubert/dev/Intellij-wss/github/sabi/sabi-webclient/sabi-webclient.conf
        dest: /var/sabi
        owner: sabi
        group: sabi
        mode: '0444'
    - name: enforce deamon config reload
      command: systemctl daemon-reload
    - name: Start sabi service
      service:
        name: sabi
        state: started
