- hosts: sabiMiddleware
  vars_files:
    - ./group_vars/sabiMiddleware.yml
  tasks:
    - name: Stop existing captcha service
      service:
        name: sabi
        state: stopped
    - name: Copy new jar file
      copy:
        src: /Users/schubert/dev/Intellij-wss/github/sabi/sabi-server/target/sabi-service-1.0-SNAPSHOT.jar
        dest: /var/sabi
        owner: sabi
        group: sabi
        mode: '0500'
    - name: Copy JVM config file
      copy:
        src: /Users/schubert/dev/Intellij-wss/github/sabi/sabi-server/sabi-service.conf
        dest: /var/sabi
        owner: sabi
        group: sabi
        mode: '0444'
    - name: enforce deamon config reload
      command: systemctl daemon-reload
    - name: Start sabi service
      service:
        name: sabi
        state: started
